// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// matWVCorr
NumericVector matWVCorr(NumericMatrix Mat, NumericVector Vec, NumericVector Vecw);
RcppExport SEXP _crestree_matWVCorr(SEXP MatSEXP, SEXP VecSEXP, SEXP VecwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Mat(MatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Vec(VecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Vecw(VecwSEXP);
    rcpp_result_gen = Rcpp::wrap(matWVCorr(Mat, Vec, Vecw));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_crestree_matWVCorr", (DL_FUNC) &_crestree_matWVCorr, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_crestree(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
