# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculate weighted correlation between columns of a matrix and a given vector
#' @export
matWVCorr <- function(Mat, Vec, Vecw) {
    .Call('_crestree_matWVCorr', PACKAGE = 'crestree', Mat, Vec, Vecw)
}

